// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyzcbdbivnthwvepdrtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5emNiZGJpdm50aHd2ZXBkcnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTc3NTgsImV4cCI6MjA2MzU5Mzc1OH0.SSTdrF1Mid3p8iYNHLy3M4DMsQHDd0RBj6wsKZWx6bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);